interface FarmField {
  id: string;
  farmId: string;
  location: [number, number][];
  area: [number, number];
  position: [number, number];
  positionMin: [number, number];
  positionMax: [number, number];
  saturation: number;
  swcInitValue: number;
  capacity: number;
  wiltingPoint: number;
  pivotFullSpeedDuration: number;
  swcStartTime: string;
  googleTransform: number[];
  s2Transform: number[];
  googleImage: string;
  googleImageDate: string;
  s2Image: string;
  s2ImageDate: string;
  estimatedStartDate: string;
  estimatedEndDate: string;
  name: string;
  cropType: string;
  plantdate: string;
  satellites: string[];
  accessAccountKeys: string[];
  SoilType: string;
  irrigationType: string;
  cropVarity: string;
  fieldArea: number;
  ageInDays: number;
  estimatedHarvestDate: string;
  referenceImgDate: string;
  emitterFlowRate: number;
  drippersPerAcre: number;
  hydraulicConductivity: number;
  depletionFactor: number;
  kcw: number;
  kcb: number;
  irrigationRisk: string;
  irrigationRiskComment: string;
  irrigationSystem: string;
  weatherRisk: string;
  yieldRisk: string;
  harvestRisk: string;
  harvestRiskComment: string;
  endDate: string;
  planetCollectionId: string;
  lastIrrigationDate: string;
  runAnalytics: boolean;
  isOnboarded: boolean;
  timezoneOffset: number;
  pivotSheets: null;
  createdBy: string;
  createdOn: string;
  modifiedBy: string;
  modifiedOn: string;
  isDeleted: boolean;
  recommendedWater: number;
}
